# Generated by Django 2.2.9 on 2019-12-23 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20191128_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['course_instance', '-pin', '-publish'], 'verbose_name': '公告', 'verbose_name_plural': '公告'},
        ),
    ]
