# Generated by Django 2.2.9 on 2019-12-23 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deviations', '0002_deadlineruledeviation_without_late_penalty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deadlineruledeviation',
            options={'verbose_name': '截止日期偏差', 'verbose_name_plural': '截止日期偏差'},
        ),
        migrations.AlterModelOptions(
            name='maxsubmissionsruledeviation',
            options={'verbose_name': '最大提交偏差', 'verbose_name_plural': '最大提交偏差'},
        ),
    ]
