# Generated by Django 2.2.7 on 2019-11-28 07:11

import course.models
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0044_auto_20190415_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinstance',
            name='archive_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='归档时间'),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='assistants',
            field=models.ManyToManyField(blank=True, related_name='assisting_courses', to='userprofile.UserProfile', verbose_name='选择助教'),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='content_numbering',
            field=models.IntegerField(choices=[(0, 'No numbering'), (1, 'Arabic'), (2, 'Roman'), (3, 'Hidden arabic')], default=1, verbose_name='章节编号'),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='ending_time',
            field=models.DateTimeField(verbose_name='结课时间'),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='enrollment_audience',
            field=models.IntegerField(choices=[(1, 'Internal users'), (2, 'External users'), (3, 'Internal and external users')], default=1, verbose_name='注册对象'),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='enrollment_ending_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='关闭注册时间'),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='enrollment_starting_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开放注册时间'),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='footer',
            field=models.TextField(blank=True, verbose_name='页脚'),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='head_urls',
            field=models.TextField(blank=True, help_text='External CSS and JS resources that are included on all course pages. Separate with white space.', verbose_name='资源URLs'),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=course.models.build_upload_dir, verbose_name='缩略图'),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='index_mode',
            field=models.IntegerField(choices=[(0, 'User results'), (1, 'Table of contents'), (2, 'Link to last visited content'), (10, 'Experimental setup (hard-coded)')], default=0, help_text='Select content for the course index page.', verbose_name='Index mode'),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='instance_name',
            field=models.CharField(max_length=255, verbose_name='课程实例'),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='language',
            field=models.CharField(blank=True, default='zh-hans', max_length=255, verbose_name='语言'),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='lifesupport_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结业时间'),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='module_numbering',
            field=models.IntegerField(choices=[(0, 'No numbering'), (1, 'Arabic'), (2, 'Roman'), (3, 'Hidden arabic')], default=1, verbose_name='模块编号'),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='starting_time',
            field=models.DateTimeField(verbose_name='开课时间'),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='technical_error_emails',
            field=models.CharField(blank=True, help_text='By default exercise errors are reported to teacher email addresses. Set this field as comma separated emails to override the recipients.', max_length=255, verbose_name='错误邮箱'),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='url',
            field=models.CharField(help_text='Input an URL identifier for this course instance.', max_length=255, validators=[django.core.validators.RegexValidator(message='URL keys may consist of alphanumeric characters, hyphen and period.', regex=re.compile('^\\w[\\w\\-\\.]*$'))], verbose_name='URL标识'),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='view_content_to',
            field=models.IntegerField(choices=[(1, 'Enrolled students'), (2, 'Enrollment audience'), (3, 'All registered users'), (4, 'Public to internet')], default=1, verbose_name='内容可见'),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='visible_to_students',
            field=models.BooleanField(default=True, verbose_name='公开课程'),
        ),
    ]
