# Generated by Django 2.2.7 on 2019-11-28 08:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import lib.fields
import re


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0045_auto_20191128_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=255, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='teaching_courses', to='userprofile.UserProfile', verbose_name='teachers'),
        ),
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.CharField(help_text='Input an URL identifier for this course.', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='URL keys may consist of alphanumeric characters, hyphen and period.', regex=re.compile('^\\w[\\w\\-\\.]*$'))], verbose_name='Urlidentifier'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='closing_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='closing_time'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='course_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_modules', to='course.CourseInstance', verbose_name='course_instance'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='introduction',
            field=models.TextField(blank=True, verbose_name='introduction'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='late_submission_deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='late_submission_deadline'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='late_submission_penalty',
            field=lib.fields.PercentField(default=0.5, help_text='Multiplier of points to reduce, as decimal. 0.1 = 10%', verbose_name='late_submission_penalty'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='late_submissions_allowed',
            field=models.BooleanField(default=False, verbose_name='late_submissions_allowed'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='opening_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='opening_time'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='points_to_pass',
            field=models.PositiveIntegerField(default=0, verbose_name='Points_to_pass'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='status',
            field=models.CharField(choices=[('hidden', 'Hidden'), ('maintenance', 'Maintenance'), ('ready', 'Ready'), ('unlisted', 'Unlisted in table of contents')], default='ready', max_length=32, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='url',
            field=models.CharField(help_text='Input an URL identifier for this module.', max_length=255, validators=[django.core.validators.RegexValidator(message='URL keys may consist of alphanumeric characters, hyphen and period.', regex=re.compile('^\\w[\\w\\-\\.]*$'))], verbose_name='Urlidentifier'),
        ),
        migrations.AlterField(
            model_name='learningobjectcategory',
            name='accept_unofficial_submits',
            field=models.BooleanField(default=False, help_text='Grade unofficial submissions after deadlines have passed or submission limits have been exceeded. The points are stored but not included in official records.', verbose_name='Accept_unofficial_submits'),
        ),
        migrations.AlterField(
            model_name='learningobjectcategory',
            name='confirm_the_level',
            field=models.BooleanField(default=False, help_text='Once exercise is graded non zero it confirms all the points on the hierarchy level. Implemented as a mandatory feedback feature.', verbose_name='Confirm_the_level'),
        ),
        migrations.AlterField(
            model_name='learningobjectcategory',
            name='course_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='course.CourseInstance', verbose_name='Course_instance'),
        ),
        migrations.AlterField(
            model_name='learningobjectcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='learningobjectcategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='learningobjectcategory',
            name='points_to_pass',
            field=models.PositiveIntegerField(default=0, verbose_name='Points_to_pass'),
        ),
        migrations.AlterField(
            model_name='learningobjectcategory',
            name='status',
            field=models.CharField(choices=[('hidden', 'Hidden'), ('nototal', 'No total points'), ('ready', 'Ready')], default='ready', max_length=32, verbose_name='Status'),
        ),
    ]
