# Generated by Django 2.1.15 on 2019-12-27 08:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import lib.fields
import re


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0046_auto_20191128_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程', 'verbose_name_plural': '课程'},
        ),
        migrations.AlterModelOptions(
            name='coursehook',
            options={'verbose_name': '课程挂钩', 'verbose_name_plural': '课程挂钩'},
        ),
        migrations.AlterModelOptions(
            name='courseinstance',
            options={'verbose_name': '课程实例', 'verbose_name_plural': '课程实例'},
        ),
        migrations.AlterModelOptions(
            name='coursemodule',
            options={'ordering': ['order', 'closing_time', 'id'], 'verbose_name': '课程模型', 'verbose_name_plural': '课程模型'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': '注册', 'verbose_name_plural': '注册'},
        ),
        migrations.AlterModelOptions(
            name='learningobjectcategory',
            options={'verbose_name': '学习对象种类', 'verbose_name_plural': '学习对象种类'},
        ),
        migrations.AlterModelOptions(
            name='studentgroup',
            options={'ordering': ['course_instance', 'timestamp'], 'verbose_name': '学生组', 'verbose_name_plural': '学生组'},
        ),
        migrations.AlterModelOptions(
            name='usertag',
            options={'ordering': ['course_instance', 'name'], 'verbose_name': '用户标签', 'verbose_name_plural': '用户标签'},
        ),
        migrations.AlterModelOptions(
            name='usertagging',
            options={'ordering': ['tag'], 'verbose_name': '用户标记', 'verbose_name_plural': '用户标记'},
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='closing_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='课程结束时间'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='course_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_modules', to='course.CourseInstance', verbose_name='课程实例'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='introduction',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='late_submission_deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='逾期提交截止时间'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='late_submission_penalty',
            field=lib.fields.PercentField(default=0.5, help_text='Multiplier of points to reduce, as decimal. 0.1 = 10%', verbose_name='逾期提交惩罚'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='late_submissions_allowed',
            field=models.BooleanField(default=False, verbose_name='是否允许逾期提交'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='name',
            field=models.CharField(max_length=255, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='opening_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='课程开放时间'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='order',
            field=models.IntegerField(default=1, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='points_to_pass',
            field=models.PositiveIntegerField(default=0, verbose_name='通过分数'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='status',
            field=models.CharField(choices=[('hidden', 'Hidden'), ('maintenance', 'Maintenance'), ('ready', 'Ready'), ('unlisted', 'Unlisted in table of contents')], default='ready', max_length=32, verbose_name='当前状态'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='url',
            field=models.CharField(help_text='Input an URL identifier for this module.', max_length=255, validators=[django.core.validators.RegexValidator(message='URL keys may consist of alphanumeric characters, hyphen and period.', regex=re.compile('^\\w[\\w\\-\\.]*$'))], verbose_name='utl标识符'),
        ),
    ]
