# Generated by Django 2.2.9 on 2019-12-23 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20190426_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-timestamp'], 'verbose_name': '通知', 'verbose_name_plural': '通知'},
        ),
    ]
