# Generated by Django 2.2.7 on 2019-11-28 07:11

from django.db import migrations, models
import django.db.models.deletion
import external_services.models


class Migration(migrations.Migration):

    dependencies = [
        ('external_services', '0011_menuitem_menu_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='access',
            field=models.IntegerField(choices=[(0, 'All students, assistants and teachers can access.'), (5, 'Only assistants and teachers can access.'), (10, 'Only teachers can access.')], default=0, verbose_name='Access'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu_group_label',
            field=models.CharField(blank=True, help_text='Places menu item under a group label.', max_length=255, null=True, verbose_name='Menu group label'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu_icon_class',
            field=models.CharField(blank=True, help_text='Menu icon style name (else service default), e.g. star see http://getbootstrap.com/components/#glyphicons-glyphs', max_length=32, null=True, verbose_name='Menu icon class'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu_label',
            field=models.CharField(blank=True, help_text='Label for the menu link (else service default).', max_length=255, null=True, verbose_name='Menu label'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu_url',
            field=models.CharField(blank=True, help_text='URL that is a) relative to the service URL or b) this course if no service is selected.\nCase a: url starting with / overwrites path in service url and extends it otherwise.\ncase b: url starting with / is absolute within this service and relative to the course path otherwise.\nNote that URL entered here can not include scheme or domain.', max_length=256, null=True, validators=[external_services.models.validate_no_domain], verbose_name='Menu url'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='service',
            field=models.ForeignKey(blank=True, help_text='An external service to link to. These are configured by administrators.', null=True, on_delete=django.db.models.deletion.CASCADE, to='external_services.LinkService', verbose_name='Service'),
        ),
    ]
