# Generated by Django 2.2.9 on 2019-12-23 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('external_services', '0012_auto_20191128_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkservice',
            options={'ordering': ['menu_label'], 'verbose_name': '链接服务', 'verbose_name_plural': '链接服务'},
        ),
        migrations.AlterModelOptions(
            name='ltiservice',
            options={'verbose_name': '学习工具互动操作服务', 'verbose_name_plural': '学习工具互动操作服务'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['course_instance', 'menu_weight', 'menu_label'], 'verbose_name': '菜单项', 'verbose_name_plural': '菜单项'},
        ),
    ]
