# Generated by Django 2.2.7 on 2019-11-28 07:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0035_auto_20190426_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseexercise',
            name='allow_assistant_grading',
            field=models.BooleanField(default=False, verbose_name='Allow assistant grading'),
        ),
        migrations.AlterField(
            model_name='baseexercise',
            name='allow_assistant_viewing',
            field=models.BooleanField(default=True, verbose_name='Allow assistant viewing'),
        ),
        migrations.AlterField(
            model_name='baseexercise',
            name='difficulty',
            field=models.CharField(blank=True, max_length=32, verbose_name='Difficulty'),
        ),
        migrations.AlterField(
            model_name='baseexercise',
            name='max_group_size',
            field=models.PositiveIntegerField(default=1, verbose_name='Max group size'),
        ),
        migrations.AlterField(
            model_name='baseexercise',
            name='max_points',
            field=models.PositiveIntegerField(default=100, verbose_name='Max points'),
        ),
        migrations.AlterField(
            model_name='baseexercise',
            name='max_submissions',
            field=models.PositiveIntegerField(default=10, verbose_name='Max submissions'),
        ),
        migrations.AlterField(
            model_name='baseexercise',
            name='min_group_size',
            field=models.PositiveIntegerField(default=1, verbose_name='Min group size'),
        ),
        migrations.AlterField(
            model_name='baseexercise',
            name='points_to_pass',
            field=models.PositiveIntegerField(default=40, verbose_name='Points to pass'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='audience',
            field=models.IntegerField(choices=[(0, 'Course audience'), (1, 'Only internal users'), (2, 'Only external users'), (3, 'Only registered users')], default=0, verbose_name='Audience'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_objects', to='course.LearningObjectCategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='course_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_objects', to='course.CourseModule', verbose_name='Course module'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='description',
            field=models.TextField(blank=True, help_text='Internal description is not presented on site.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='model_answers',
            field=models.TextField(blank=True, help_text='List model answer files as protected URL addresses.', verbose_name='Model answers'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='exercise.LearningObject', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='service_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Service url'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='status',
            field=models.CharField(choices=[('enrollment', 'Enrollment questions'), ('enrollment_ext', 'Enrollment questions for external students'), ('hidden', 'Hidden from non course staff'), ('maintenance', 'Maintenance'), ('ready', 'Ready'), ('unlisted', 'Unlisted in table of contents')], default='ready', max_length=32, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='templates',
            field=models.TextField(blank=True, help_text='List template files as protected URL addresses.', verbose_name='Templates'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='url',
            field=models.CharField(help_text='Input an URL identifier for this object.', max_length=255, validators=[django.core.validators.RegexValidator(message='URL keys may consist of alphanumeric characters, hyphen and period.', regex=re.compile('^\\w[\\w\\-\\.]*$'))], verbose_name='Urlidentifier'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='use_wide_column',
            field=models.BooleanField(default=False, help_text='Remove the third info column for more space.', verbose_name='use wide column'),
        ),
    ]
