# Generated by Django 2.2.7 on 2019-11-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0036_auto_20191128_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursechapter',
            name='generate_table_of_contents',
            field=models.BooleanField(default=False, verbose_name='Generate_table_of_contents'),
        ),
    ]
