# Generated by Django 2.2.9 on 2019-12-23 09:27

from django.db import migrations, models
import django.db.models.deletion
import exercise.exercise_models
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0037_auto_20191129_0858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseexercise',
            options={'verbose_name': '基础练习', 'verbose_name_plural': '基础练习'},
        ),
        migrations.AlterModelOptions(
            name='coursechapter',
            options={'verbose_name': '课程章节', 'verbose_name_plural': '课程章节'},
        ),
        migrations.AlterModelOptions(
            name='exercisewithattachment',
            options={'verbose_name': '带附件的练习', 'verbose_name_plural': '带附件的练习'},
        ),
        migrations.AlterModelOptions(
            name='learningobject',
            options={'ordering': ['course_module', 'order', 'id'], 'verbose_name': '学习对象', 'verbose_name_plural': '学习对象'},
        ),
        migrations.AlterModelOptions(
            name='staticexercise',
            options={'verbose_name': '静态练习', 'verbose_name_plural': '静态练习'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-id'], 'verbose_name': '提交', 'verbose_name_plural': '提交'},
        ),
        migrations.AlterModelOptions(
            name='submittedfile',
            options={'verbose_name': '提交的文件', 'verbose_name_plural': '提交的文件'},
        ),
        migrations.AlterField(
            model_name='exercisewithattachment',
            name='attachment',
            field=models.FileField(upload_to=exercise.exercise_models.build_upload_dir, verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='exercisewithattachment',
            name='files_to_submit',
            field=models.CharField(blank=True, help_text='File names that user should submit, use pipe character to separate files', max_length=200, verbose_name='需要提交的文件'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='content',
            field=models.TextField(blank=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='ltiexercise',
            name='context_id',
            field=models.CharField(blank=True, help_text='Default: [hostname]/[course:url]/[instance:url]/', max_length=128, verbose_name='内容id'),
        ),
        migrations.AlterField(
            model_name='ltiexercise',
            name='lti_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='external_services.LTIService', verbose_name='LTI服务'),
        ),
        migrations.AlterField(
            model_name='ltiexercise',
            name='resource_link_id',
            field=models.CharField(blank=True, help_text='Default: [aplusexercise:id]', max_length=128, verbose_name='资源链接id'),
        ),
        migrations.AlterField(
            model_name='ltiexercise',
            name='resource_link_title',
            field=models.CharField(blank=True, help_text='Default: the menu label of the LTI service', max_length=128, verbose_name='资源链接名称'),
        ),
        migrations.AlterField(
            model_name='staticexercise',
            name='exercise_page_content',
            field=models.TextField(verbose_name='练习页面内容'),
        ),
        migrations.AlterField(
            model_name='staticexercise',
            name='submission_page_content',
            field=models.TextField(verbose_name='提交页面内容'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assistant_feedback',
            field=models.TextField(blank=True, verbose_name='助教反馈'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True, verbose_name='反馈'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='grade',
            field=models.IntegerField(default=0, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='grading_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='评分时间'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='late_penalty_applied',
            field=lib.fields.PercentField(blank=True, null=True, verbose_name='逾期扣分适用'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('error', 'Error'), ('initialized', 'Initialized'), ('ready', 'Ready'), ('rejected', 'Rejected'), ('unofficial', 'No effect on grading'), ('waiting', 'In grading')], default='initialized', max_length=32, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='提交日期'),
        ),
    ]
