# Generated by Django 2.1.15 on 2019-12-31 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0038_auto_20191223_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobject',
            name='comments',
            field=models.TextField(blank=True, verbose_name='评论'),
        ),
    ]
