# Generated by Django 2.2.9 on 2019-12-23 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0002_coursediplomadesign_availability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursediplomadesign',
            options={'verbose_name': '设计课程证书', 'verbose_name_plural': '设计课程证书'},
        ),
        migrations.AlterModelOptions(
            name='studentdiploma',
            options={'verbose_name': '学生证书', 'verbose_name_plural': '学生证书'},
        ),
    ]
