# Generated by Django 2.2.9 on 2019-12-23 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20150527_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseplugin',
            options={'verbose_name': '基本插件', 'verbose_name_plural': '基本插件'},
        ),
        migrations.AlterModelOptions(
            name='basetab',
            options={'ordering': ['order', 'id'], 'verbose_name': '基本标签', 'verbose_name_plural': '基本标签'},
        ),
        migrations.AlterModelOptions(
            name='externalembeddedtab',
            options={'verbose_name': '外部嵌入式标签', 'verbose_name_plural': '外部嵌入式标签'},
        ),
        migrations.AlterModelOptions(
            name='externaliframeplugin',
            options={'verbose_name': '外部iframe插件', 'verbose_name_plural': '外部iframe插件'},
        ),
        migrations.AlterModelOptions(
            name='externaliframetab',
            options={'verbose_name': '外部iframe标签', 'verbose_name_plural': '外部iframe标签'},
        ),
        migrations.AlterModelOptions(
            name='htmlplugin',
            options={'verbose_name': 'HTML插件', 'verbose_name_plural': 'HTML插件'},
        ),
        migrations.AlterModelOptions(
            name='htmltab',
            options={'verbose_name': 'HTML标签', 'verbose_name_plural': 'HTML标签'},
        ),
        migrations.AlterModelOptions(
            name='rssplugin',
            options={'verbose_name': 'Rss插件', 'verbose_name_plural': 'Rss插件'},
        ),
    ]
