# Generated by Django 2.2.9 on 2019-12-23 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threshold', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemodulerequirement',
            options={'verbose_name': '课程模块的需求', 'verbose_name_plural': '课程模块的需求'},
        ),
        migrations.AlterModelOptions(
            name='threshold',
            options={'verbose_name': '阈值', 'verbose_name_plural': '阈值'},
        ),
    ]
